Merge from shopify/main (#1)
* Add support for minitest-focus

* Bump version to v1.0.1

* Remove uneccassary require statement.

I'm removing the require statement for ConstantNameInspector in the main
packwerk file. The class is require at the file that uses it and doesn't
need to be specified a second time.

* add class method to check if node is a constant

I'm adding a `.constant?` class method to the Node class to check if a
node instance is a constant or not.

Before this change we would use `Node.type(node) == Node::CONSTANT` to
check if a node is a constant. This however exposes too many internals
 and can be abstracted into a class method, which makes the code easier
 to understand.

* add fully_qualify_constant private method

I'm moving a chunk of code out of the constant_name_from_node method.
This makes the intend clearer.

* Update USAGE.md

* Fix Gemfile.lock

* Correct Referenced Constant

`has_many :birds` should look up the `Bird` constant, not `Birds`

* Refactor Inflector to be more testable and add new constructor

Co-authored-by: Tom Stuart <tom.stuart@shopify.com>

* Use a different custom inflections file in “mismatched inflections” test

We want to be able to use `custom_inflections.yml` to test the
application validation check, since it contains useful inflections that
the app actually uses. When we fix the inflector in a subsequent commit
we’ll need to add `custom_inflections.yml` to its `packwerk.yml`, so we
should use a different set of inflections in this test that’s
intentionally trying to create a mismatch.

* Use new Inflector constructor in run context

`payment_details` in `custom_inflections.yml` is an "uncountable",
which means it should not be inflected when found in a constant association.

Without the fix for this bug, `has_one :payment_details` would not be a
violation because Packwerk is unable to resolve it to a constant and
treats it as a non-violation. In reality, `PaymentDetails` exists as a
constant, which makes it a legitimate violation. See:

https://github.com/Shopify/packwerk/issues/48

In lockstep with this change it was necessary to give the skeleton
application the ability to load its custom inflections, since that’s
what the application validity checker is checking. (This wasn’t a
problem before because Packwerk wasn’t loading the custom inflections
either, but that’s the bug being fixed.)

Co-authored-by: Tom Stuart <tom.stuart@shopify.com>

* Use the correct inflector in the application validator checker

Co-authored-by: Tom Stuart <tom.stuart@shopify.com>

* cleanup guard method to have conditional in private method

* Update pull_request_template.md

* Make custom_inflector argument in Inflector required

This means we have to make the `inflector` argument in
`AssociationInspector` required too, since it was relying on this
default. That’s fine in practice because (aside from the tests) only
`RunContext` instantiates `AssociationInspector`, and it always supplies
an `inflector`.

Co-authored-by: Tom Stuart <tom.stuart@shopify.com>

* exclude static directory from gem

* add process_file method to RunContext

I'm changing the RunContext class not to leak the file processor object
to the CLI class. This change is reducing how complected the two classes are.

I'm doing this change so that I can pass a NodeProcessorFactory to the
FileProcessor instead of a RunContext instance. If I wouldn't
introducee this change, I would have to make the CLI aware of the
NodeProcessorFactory, which would leak too many implementation details.

* replace RunContext with NodeProcessorFactory instance in the
FileProcessor

This commit changes a dependency of the FileProcessor class from the
RunContext class to a more narrowly defined NodeProcessorFactory.

* remove duplicate default reference listener assignment

The default reference_listener assignment is done in the initializer and
the from_configuration class method. This duplication makes the code
hard to reason about. So I'm removing the latter one, because the rest
of the defaults are set in the initializer.

* access filename through reference

The filename and Reference#relative_path are the same values. I decided
to change it to the latter one because the method primarily uses the reference object.
Using the reference object instead reduces how much knowledge the method
has to have.

* remove path expansion for root path

The path that gets passed into the run context is already expaneded so
we don't have to do it again.

* move object initializations into private methods

This commit cleans up the initializer of the RunContext by moving
non-assignment operations into private methods.

It wasn't clear in what order each instance variable assignment should have been, which made it hard to reason about the class.

* add missing attr readers

as per shopify styleguide instance methods should be accessed through
attr_reader methods.

* Remove NodeProcessor dependency injection from RunContext.

This commit removes the class injection of the NodeProcess class into
the RunContext class. This is a capability that isn't used in the code
and with the addition of the the NodeProcessorFactory is not neccessary
at the RunContext level.

* move reference_listener initialization from RunContext into Cli class

The CheckingDeprecatedReferences and UpdatingDeprecatedReferences class, both are concerned with producing a type of output for the user of packwerk. As such, the initialization should happen outside the NodeProcessorBuilder and rather in the Cli class.

* extract CacheDeprecatedReferences superclass from UpdatingDeprecatedReferences class to support other functionality such as detecting stale deprecations

* add .class? predicate method

* add constant_assignment? predicate

* change remaning usage of type method to predicate methods

* make type method private

* rename type to type_of

* Support setting the Erb parser on the factory

* Split reading the file from parsing the buffer

* Document how to set the custom ERB parser class

* update sorbet-runtime

* prevent stubbing methods that don't exist through mocha

* increase type safety in validator test

* Make load path extraction logic testable

* Add .realpath back to #package_manifests

* Add space for readability

* Return unique load paths for `ApplicationLoadPaths#extract_relevant_paths`

* Bump Packwerk to v1.0.2

* add method to check for stale violations within DeprecatedReferences class as well as associated unit tests

* created DetectStaleDeprecatedReferences class which can be used to check for stale violations as a reference lister. In addition wrote unit tests for this class

* created new class DetectStaleViolationsCommand in order to test easily the functionality of dectect-stale-violations function in cli.rb

* Have ApplicationValidator load packages from config root instead of current working directory

* Support array of paths in PackageSet

* .reference_qualifications generates all possible qualifications for a reference even when there are nil nodes in the namespace path

* Make node.type return nil for nil nodes

* Prevent processing from breaking on unusual constants

* Use each_with_object instead of reduce

* Prevent erring out on self nodes without wide rescue

* Improve test naming for self:: node parsing fix

* Remove node type protection against nil node

* bump packwerk version for new release v1.1.0

* Fix CLI init by defining default load path value

`ConfigurationFile#initialize` is expecting an Array value for `load_paths`,
yet when called via the `packwerk init` CLI command, it was being passed as
`nil` and thus throwing a Sorbet type violation.

This restores the prior behaviour of loading the application load paths to
pass to the configuration file generator.

I'm also providing an empty array as a fallback for `load_paths` when loading
a configuration file. This is expected to be an array elsewhere, so this
covers us if the config file doesn't have it defined.

* Define FixtureHelper module and :minimal fixure application

* Use FixtureHelper in Configuration test suite

* Fix warnings

* Set typed: false on all test helper classes, SanityChecker, and SpringCommand

* Clean up existing ApplicationValidator tests

* Implement RailsApplicationTestHelper

* Use RailsApplicationFixtureHelper in ApplicationValidatorTest

* Improve coverage for ApplicationValidator

* Refactor CLI: Update Deprecations

* Add Commands module to existing DetectStaleViolationsCommand

* Use typed: strict for new files and refactor Result

* Refactor OffensesFormatter

* Final tweaks

* Ensure parsed configuration is a Hash

Setting up packwerk caused a bug during the initial `packwerk check`:

```
bundler: failed to load command: packwerk (/Users/alexblackie/.gem/ruby/2.6.6/bin/packwerk)
NoMethodError: undefined method `[]' for false:FalseClass
  /Users/alexblackie/.gem/ruby/2.6.6/gems/packwerk-1.1.0/lib/packwerk/configuration.rb:39:in `initialize'
  /Users/alexblackie/.gem/ruby/2.6.6/gems/packwerk-1.1.0/lib/packwerk/configuration.rb:25:in `new'
```

This appears to have been because the YAML configuration file that is
generated is empty (comments only) by default, causing `load_file` to
return `false` because it isn't yet a valid YAML document.

To ensure we comply with the API of `Configuration`, we should ensure
any falsey values get turned into an empty hash.

Co-authored-by: Jacob Erickson <jacob.erickson@shopify.com>

* Convert more tests to using application fixture helpers

* bump packwerk version for new release v1.1.1

* give more helpful error message if privatized constant can not be resolved

* prevent packages from defining other packages constants as private

* refactor check_package_manifests_for_privacy and tweak error message

* Move to typed: strict on implementations of Packwerk::ConstantNameInspector

* Add missing #violation_type method to Packwerk::Checker interface

* Move to typed: strict on implementations of Packwerk::Checker

Fixes nil returns where return type was T::Boolean along the way

* Move to typed: strict where possible on Packwerk::ReferenceLister implementations

* Fix CheckingDeprecatedReferencesTest not working alongside strict types

* Add sig to Node.parent_module_name & remove unreachable code

* Add type alias for any output style

* Move to using type alias for output styles over local T.any T.class_of

* Update README.md

* Add sig’s covering all uses of output style

Using fake test doubles to keep Cli tests happy

* Move output style to being interface backed

* Convert autoload paths to strings to prevent sorbet error related to Pathname

* Update packwerk update-deprecations cmd

* bump packwerk version for new release v1.1.2

* Add inspirational quote

Get readers into the right mood 😄

* Update library.yml

* Add development status note

* Clarify development status note

A point was raised in the the [https://rubymod.slack.com/](Ruby Modularity Slack) that the current messages could be interpreted as the project no longer being used at Shopify. I've updated the message to add some context from #102.

cc @gmcgibbon

* Fix wording

* Update ownership of Packwerk

Co-authored-by: Roch Lefebvre <roch.lefebvre@shopify.com>
Co-authored-by: Cory Hutchison <cory.hutchison@shopify.com>
Co-authored-by: Frederik Dudzik <frederik.dudzik@shopify.com>
Co-authored-by: Edward Ocampo-Gooding <edward@shopify.com>
Co-authored-by: Cory Hutchison <cjhutchi@users.noreply.github.com>
Co-authored-by: Maple Ong <maple.ong@shopify.com>
Co-authored-by: Steven Nunez <octosteve@github.com>
Co-authored-by: Tom Stuart <tom.stuart@shopify.com>
Co-authored-by: Frederik Dudzik <5946811+doodzik@users.noreply.github.com>
Co-authored-by: Matt Clark <44023+mclark@users.noreply.github.com>
Co-authored-by: Cindy Gao <cindy.gao@shopify.com>
Co-authored-by: Philip Müller <mail@philip.in-aachen.net>
Co-authored-by: Josh Abernathy <josh@github.com>
Co-authored-by: Philip Müller <philip.mueller@shopify.com>
Co-authored-by: cindygshopify <59701253+cindygshopify@users.noreply.github.com>
Co-authored-by: Stephan Hagemann <stephan.hagemann@gusto.com>
Co-authored-by: Mikel Kew <mikel@bikeroar.com>
Co-authored-by: Santiago Bartesaghi <santib@hey.com>
Co-authored-by: Alex Blackie <alex@alexblackie.com>
Co-authored-by: Jacob Erickson <jacob.erickson@shopify.com>
Co-authored-by: Samuel Giles <sam@samuelgil.es>
Co-authored-by: Steven Low <steven.low@shopify.com>
Co-authored-by: Thierry Joyal <thierry.joyal@gmail.com>
Co-authored-by: Gannon McGibbon <gannon.mcgibbon@shopify.com>
Co-authored-by: Andy Waite <andyw8@users.noreply.github.com>
Co-authored-by: Rafael França <rafael.franca@shopify.com>
Co-authored-by: Gabi Stefanini <lastgabs@users.noreply.github.com>